### ISSUE TITLE
zopfli gzip?

### ISSUE THREAD

**Issue by tomByrer** [markdalgleish/grunt-micro#1]
Might be able to squeeze a few more bytes in using this compressor.  Slower than 7zip, but for only a few kb file, won't matter.
http://ckon.wordpress.com/2013/03/02/zopfli-gzip-compressor-on-windows/

**Comment by markdalgleish** [comment]
This plugin uses [zlib-browserify](https://github.com/brianloveswords/zlib-browserify) because that's the same module used to calculate [MicroJS](http://microjs.com/) eligibility.

**Comment by tomByrer** [comment]
Thanks for the insight!
